[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
workingDir = "app"
commands = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn -b 0.0.0.0:5000 app:app"
