version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net

  flask-app:
    build:
      context: /app
      dockerfile: /app/Dockerfile
    container_name: flask-app
    # expose:
    #   - "5000"  # Expose port to the network (not mapped to the host)
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    depends_on:
      - redis
    networks:
      - redis-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Map your custom nginx.conf
      - ./ssl:/etc/nginx/ssl  # Map your SSL certificates directory
      - ./app/static:/app/static
    depends_on:
      - flask-app
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
